### ISSUE TITLE
Numpy 2.0 Released - `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead

### ISSUE THREAD

**Issue by DarkCTO** [mito-ds/mito#1310]
**Describe the bug**
```
Traceback (most recent call last):
  File "c:\Users\Documents\Project\Python\MyApp\Main.py", line 21, in <module>
    from mitosheet.mito_dash.v1 import Spreadsheet, mito_callback
  File "C:\Users\Documents\Project\Python\venv\venv_311\Lib\site-packages\mitosheet\__init__.py", line 30, in <module>
    from mitosheet.mito_backend import sheet
  File "C:\Users\Documents\Project\Python\venv\venv_311\Lib\site-packages\mitosheet\mito_backend.py", line 24, in <module>
    from mitosheet.api import API
  File "C:\Users\Documents\Project\Python\venv\venv_311\Lib\site-packages\mitosheet\api\__init__.py", line 1, in <module>
    from mitosheet.api.api import API
  File "C:\Users\Documents\Project\Python\venv\venv_311\Lib\site-packages\mitosheet\api\api.py", line 14, in <module> 
    from mitosheet.api.get_saved_analysis_code import get_saved_analysis_code
  File "C:\Users\Documents\Project\Python\venv\venv_311\Lib\site-packages\mitosheet\api\get_saved_analysis_code.py", line 2, in <module>
    from mitosheet.saved_analyses.save_utils import read_analysis
  File "C:\Users\Documents\Project\Python\venv\venv_311\Lib\site-packages\mitosheet\saved_analyses\__init__.py", line 7, in <module>
    from mitosheet.saved_analyses.save_utils import (
  File "C:\Users\Documents\Project\Python\venv\venv_311\Lib\site-packages\mitosheet\saved_analyses\save_utils.py", line 11, in <module>
    from mitosheet.step import Step
  File "C:\Users\Documents\Project\Python\venv\venv_311\Lib\site-packages\mitosheet\step.py", line 10, in <module>    
    from mitosheet.step_performers.step_performer import StepPerformer
  File "C:\Users\Documents\Project\Python\venv\venv_311\Lib\site-packages\mitosheet\step_performers\__init__.py", line 12, in <module>
    from mitosheet.step_performers.concat import ConcatStepPerformer
  File "C:\Users\Documents\Project\Python\venv\venv_311\Lib\site-packages\mitosheet\step_performers\concat.py", line 10, in <module>
    from mitosheet.code_chunks.step_performers.concat_code_chunk import \
  File "C:\Users\Documents\Project\Python\venv\venv_311\Lib\site-packages\mitosheet\code_chunks\step_performers\concat_code_chunk.py", line 10, in <module>
    from mitosheet.state import State
  File "C:\Users\Documents\Project\Python\venv\venv_311\Lib\site-packages\mitosheet\state.py", line 14, in <module>   
    from mitosheet.utils import  get_first_unused_dataframe_name
  File "C:\Users\Documents\Project\Python\venv\venv_311\Lib\site-packages\mitosheet\utils.py", line 37, in <module>   
    from mitosheet.public.v3.formatting import add_formatting_to_excel_sheet
  File "C:\Users\Documents\Project\Python\venv\venv_311\Lib\site-packages\mitosheet\public\v3\__init__.py", line 1, in <module>
    from mitosheet.public.v2 import (
  File "C:\Users\Documents\Project\Python\venv\venv_311\Lib\site-packages\mitosheet\public\v2\__init__.py", line 2, in <module>
    from mitosheet.public.v1 import (
  File "C:\Users\Documents\Project\Python\venv\venv_311\Lib\site-packages\mitosheet\public\v1\__init__.py", line 4, in <module>
    from mitosheet.public.v1.sheet_functions import FUNCTIONS
  File "C:\Users\Documents\Project\Python\venv\venv_311\Lib\site-packages\mitosheet\public\v1\sheet_functions\__init__.py", line 9, in <module>
    from mitosheet.public.v1.sheet_functions.number_functions import *
  File "C:\Users\Documents\Project\Python\venv\venv_311\Lib\site-packages\mitosheet\public\v1\sheet_functions\number_functions.py", line 24, in <module>
    from mitosheet.public.v1.sheet_functions.types.decorators import (
  File "C:\Users\Documents\Project\Python\venv\venv_311\Lib\site-packages\mitosheet\public\v1\sheet_functions\types\__init__.py", line 12, in <module>
    from mitosheet.public.v1.sheet_functions.types.to_boolean_series import to_boolean_series
  File "C:\Users\Documents\Project\Python\venv\venv_311\Lib\site-packages\mitosheet\public\v1\sheet_functions\types\to_boolean_series.py", line 22, in <module>
    on_uncastable_arg_element: Any=('default', np.NaN), # Union[Literal['error'], Tuple[Literal['default'], any]]
                                               ^^^^^^
  File "C:\Users\Documents\Project\Python\venv\venv_311\Lib\site-packages\numpy\__init__.py", line 411, in __getattr__    raise AttributeError(
AttributeError: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.. Did you mean: 'nan'?
```

**To Reproduce**
Use Mitosheet
I use it in my Dash app

Please include the relevant dataset if the bug you encountered is dataset specific. Make sure to anonymize the data properly.

**Expected behavior**
No error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Browser [e.g. Chrome, Firefox]
 - Mito Version [e.g. 0.3.331] (you can find this with `pip list`)

**Additional context**
Since this is released 6 days ago, it is understandable this hasn't fixed yet.
But it's worth getting your attention.

**Comment by naterush** [comment]
@DarkCTO fix coming today for this. Thanks for the report
