### ISSUE TITLE
Development install fails in Python 3.12

### ISSUE THREAD

**Issue by ktaletsk** [mito-ds/mito#1425]
**Describe the bug**
Development install of Mito AI fails when using Python 3.12

**To Reproduce**

1. Create environment
```
mamba create -n mito python=3.12 nodejs=20 jupyterlab
```
2. Install mitosheet
3. Install `mito-ai` in development mode
```
touch yarn.lock
pip install -e ".[test, deploy]"
jlpm install
jlpm build
jupyter labextension develop . --overwrite
```

The error reported is 
```
Traceback (most recent call last):
  File "/path/to/mito/mito-ai/setup.py", line 3, in <module>
    from setuptools import setup, find_packages
  File "/Users/ktaletsk/mamba/envs/mito/lib/python3.12/site-packages/setuptools/__init__.py", line 10, in <module>
    import distutils.core
ModuleNotFoundError: No module named 'distutils'
/Users/ktaletsk/mamba/envs/mito/lib/python3.12/site-packages/jupyterlab/debuglog.py:54: UserWarning: An error occurred.
  warnings.warn("An error occurred.")
/Users/ktaletsk/mamba/envs/mito/lib/python3.12/site-packages/jupyterlab/debuglog.py:55: UserWarning: FileNotFoundError: The Python package `.` is not a valid package, it is missing the `setup.py` file.
  warnings.warn(msg[-1].strip())
/Users/ktaletsk/mamba/envs/mito/lib/python3.12/site-packages/jupyterlab/debuglog.py:56: UserWarning: See the log file for details: /var/folders/p0/ct1ct0q57bl9_k9tpcsjcc700000gn/T/jupyterlab-debug-hy9z43nx.log
  warnings.warn(f"See the log file for details: {log_path!s}")
  ```

**Comment by ktaletsk** [comment]
It's a good idea to switch to rebuild using the latest extension cookiecutter, which uses hatchling
https://github.com/jupyterlab/extension-cookiecutter-ts/tree/4.0

**Comment by aarondr77** [comment]
I think this is going to be fixed by this https://github.com/mito-ds/mito/pull/1476
