### ISSUE TITLE
Unique in Left & Unique in Right are broken

### ISSUE THREAD

**Issue by aarondr77** [mito-ds/mito#450]
They throw an error if a value is missing from a dataframe. TODO explore this more... 

```
Traceback (most recent call last):
  File "mito_widget.py", line 197, in receive_message
    self.handle_edit_event(event)
  File "mito_widget.py", line 122, in handle_edit_event
    self.steps_manager.handle_edit_event(event)
  File "steps_manager.py", line 382, in handle_edit_event
    self.execute_and_update_steps(new_steps)
  File "steps_manager.py", line 573, in execute_and_update_steps
    final_steps = execute_step_list_from_index(
  File "steps_manager.py", line 88, in execute_step_list_from_index
    new_step.set_prev_state_and_execute(last_valid_step.final_defined_state)
  File "step.py", line 147, in set_prev_state_and_execute
    post_state_and_execution_data = self.step_performer.execute(new_prev_state, params)
  File "merge.py", line 59, in execute
    new_df = _execute_merge(
  File "merge.py", line 150, in _execute_merge
    return df_one_cleaned.copy(deep=True)[bool_index_array][selected_columns_one].reset_index(drop=True)
  File "frame.py", line 3496, in __getitem__
    return self._getitem_bool_array(key)
  File "frame.py", line 3549, in _getitem_bool_array
    key = check_bool_indexer(self.index, key)
  File "indexing.py", line 2383, in check_bool_indexer
    raise IndexingError(
pandas.core.indexing.IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).

```

**Comment by naterush** [comment]
@aarondr77 I added tests for this. I cannot replicate it. Assuming that a missing value means a NaN value?

**Comment by aarondr77** [comment]
I'll figure out a test case for this if it comes up again.

**Comment by aarondr77** [comment]
I created a fuzz tester to try to figure out what the error is and wasn't able to catch anything. 

```
import random
import math
import string
import pandas as pd

def unique_in_left_merge_df1(df1, df2):
    # Merged df1 and df2 into df3
    df2_tmp = df2.drop_duplicates(subset=['C'])
    bool_index_array = df1.merge(df2_tmp, left_on=['A'], right_on=['C'], how='left', indicator=True)['_merge'] == 'left_only'
    df3 = df1.copy(deep=True)[bool_index_array][['A', 'B']].reset_index(drop=True)
    
def unique_in_left_merge_df2(df2, df1):
    # Merged df2 and df1 into df4
    df1_tmp = df1.drop_duplicates(subset=['A'])
    bool_index_array = df2.merge(df1_tmp, left_on=['C'], right_on=['A'], how='left', indicator=True)['_merge'] == 'left_only'
    df4 = df2.copy(deep=True)[bool_index_array][['C', 'D']].reset_index(drop=True)

def unique_in_right_merge_df1(df1, df2):
    # Merged df1 and df2 into df3
    df1_tmp = df1.drop_duplicates(subset=['A'])
    bool_index_array = df1_tmp.merge(df2, left_on=['A'], right_on=['C'], how='right', indicator=True)['_merge'] == 'right_only'
    df3 = df2.copy(deep=True)[bool_index_array][['C', 'D']].reset_index(drop=True)
    
def unique_in_right_merge_df2(df1, df2):
    # Merged df2 and df1 into df4
    df2_tmp = df2.drop_duplicates(subset=['C'])
    bool_index_array = df2_tmp.merge(df1, left_on=['C'], right_on=['A'], how='right', indicator=True)['_merge'] == 'right_only'
    df4 = df1.copy(deep=True)[bool_index_array][['A', 'B']].reset_index(drop=True)

    
def get_random_char(N):
    if random.uniform(0, 1) > .1:
        return ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(N))
    else:
        return None
    

def fuzz():
    N = 5
    TOTAL_ROWS = 50
    for i in range(1000):
        df1_rows = math.floor(random.uniform(0, 1) * TOTAL_ROWS)
        df2_rows = math.floor(random.uniform(0, 1) * TOTAL_ROWS)

        df1_a = [get_random_char(N) for x in range (df1_rows)]
        df1_b = [get_random_char(N) for x in range (df1_rows)]
        df2_a = [get_random_char(N) for x in range (df2_rows)]
        df2_b = [get_random_char(N) for x in range (df2_rows)]
        failed_on = ''
        try:
            df1 = pd.DataFrame({'A': df1_a, 'B': df1_b})
            df2 = pd.DataFrame({'C': df1_a, 'D': df1_b})
            failed_on = 'failed on: unique_in_left_merge(df1, df2)'
            unique_in_left_merge_df1(df1, df2)
            failed_on = 'failed on: unique_in_left_merge(df2, df1)'
            unique_in_right_merge_df2(df1, df2)
            failed_on = 'failed on: unique_in_right_merge(df1, df2)'
            unique_in_right_merge_df1(df1, df2)
            failed_on = 'failed on: unique_in_right_merge(df2, df1)'
            unique_in_right_merge_df2(df1, df2)
        except Exception as e:
            print(e)
            print('iteration: ', i)
            print(failed_on)
            print('df1_a: ', df1_a)
            print('df1_b: ', df1_b)
            print('df2_a: ', df2_a)
            print('df2_b: ', df2_b)
            break
        
    print('no error')
fuzz()       

```

**Comment by naterush** [comment]
@aarondr77 the datasets from the recon workflow are broken for unique in left and unique in right. All you have to do is extract the IDs, turn them both to strings, and try and merge them. It breaks - haven't had time to dig into why.
